### ISSUE TITLE
ephys signal generator

### ISSUE THREAD

**Issue by ChangQing-SH** [rwarren2163/SignalBuddy#3]
Hi, 
there is one called hs-tester from white matter.
https://white-matter.com/products/accessories

Does this signalbuddy perform the same function?

**Comment by richard-warren** [comment]
Hi - I'm unfamiliar with this product, but it looks as though it's meant to testing headstages. SignalBuddy is a general purpose signal generator with output in the range of 0-5V, which is appropriate for controlling laboratory hardware devices, e.g. lasers and current generators.
